# Generated by Django 3.1.1 on 2020-09-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_wsndetails_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsndetails',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
