# Generated by Django 3.1.1 on 2020-09-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_wsn_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsn',
            name='rssi',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
