# Generated by Django 3.1.1 on 2020-09-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_captcha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captcha',
            old_name='new',
            new_name='isNew',
        ),
    ]
