# Generated by Django 3.1.1 on 2020-09-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20200912_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='text',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
