# Generated by Django 3.1.1 on 2020-09-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_captcha_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captcha',
            name='isNew',
        ),
        migrations.AddField(
            model_name='captcha',
            name='state',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
